# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

name: Vita.Identity

trigger:
  branches:
    include:
    - develop
    - master
    - feature/*
  paths:
    exclude:
    - '**/Vita.API/**'
    - '**/Vita.SPA/**'

pool:
  vmImage: 'windows-latest'

variables:
  apiProjects: '**/Vita.Identity/**/*.csproj'
  apiHostProject: '**/Vita.Identity/**/Vita.Identity.Host.csproj'
  buildConfiguration: 'Release'
  ConnectionStrings.VitaIdentityDbContext: 'DB'
  Api.BaseUrl: $(vitaApiBaseUrl)
  IdentityServer.Clients.0.ClientUri: $(spaUrl)
  IdentityServer.Clients.0.RedirectUris: [ $(spaUrl)/login ]

steps:
- task: NuGetToolInstaller@1

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: $(apiProjects)
    feedsToUse: 'select'
    vstsFeed: 'd4d4328d-23fb-4700-a85b-694186019d4e/5bee72dc-d135-4e9c-84ec-df7c2fe16086'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '$(apiHostProject)'
    arguments: '--configuration $(buildConfiguration) -o $(Build.ArtifactStagingDirectory)/build/'

- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/build'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    replaceExistingArchive: true
  displayName: 'Packing Build Results'

- task: AzureRmWebAppDeployment@4
  inputs:
    ConnectionType: 'AzureRM'
    azureSubscription: 'Azure Connection'
    appType: 'webApp'
    WebAppName: 'identity-vita-dev'
    packageForLinux: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
    enableCustomDeployment: true
    DeploymentType: 'webDeploy'
    RemoveAdditionalFilesFlag: true
    JSONFiles: '**/appsettings.json'
