# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - develop
    - master
    - feature/*
  paths:
    exclude:
    - Vita.Identity/**
    - Vita.API/**

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: /Vita.SPA
    script: |
      npm install -g @angular/cli
      npm install
  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: /Vita.SPA
    script: |
      ng build --prod
  displayName: 'Build Angular SPA'