# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Vita.SPA

trigger:
  branches:
    include:
    - develop
    - master
    - feature/*
  paths:
    exclude:
    - Vita.API/*
    - Vita.Identity/*

pool:
  vmImage: 'ubuntu-latest'

variables:
  SPADirectory: $(System.DefaultWorkingDirectory)/Vita.SPA

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(SPADirectory)
    script: |
      npm install -g @angular/cli
  displayName: 'Install angular/cli'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(SPADirectory)
    script: |
        npm install
  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(SPADirectory)
    script: |
      ng build --prod
  displayName: 'Build Angular SPA'

- task: AzureFileCopy@4
  inputs:
    SourcePath: '$(SPADirectory)/dist'
    azureSubscription: 'Azure Connection'
    Destination: 'AzureBlob'
    storage: 'vitadevstg'
    ContainerName: 'spa'
  displayName: 'Deploy spa into the blob storage'