# Node.js with Angular
# Build a Node.js project that uses Angular.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

name: Vita.SPA

trigger:
  branches:
    include:
    - develop
    - master
    - feature/*
  paths:
    exclude:
    - Vita.API/*
    - Vita.Identity/*

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(System.DefaultWorkingDirectory)/Vita.SPA
    script: |
      npm install -g @angular/cli
  displayName: 'Install angular/cli'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(System.DefaultWorkingDirectory)/Vita.SPA
    script: |
        npm install
  displayName: 'npm install'

- task: Bash@3
  inputs:
    targetType: 'inline'
    workingDirectory: $(System.DefaultWorkingDirectory)/Vita.SPA
    script: |
      ng build --prod
  displayName: 'Build Angular SPA'